
title: La cucina di Lodi
title-img: /img/title.png
email: cucina.di.lodi@gmail.com
tagline:             'Pensieri, ricette...'
description: #> # this means to ignore newlines until "baseurl:"
  Dal 1987 Pasta Fresca e Corsi di Cucina
baseurl: "" # the subpath of your site, e.g. /blog
url: http://cucina-di-lodi.com # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

paginate:            4
paginate_path: "/blog/page:num/"
excerpt_separator: <!--continua-->


copyright: Copyright © 2017 LODI. All rights reserved.
credits: Site based on Jekyll and Bootstrap.
#add link to gioele github

collections:
    pasta:
    carosello:
    evidenza:

# ----------------------- #
#         Contacts        #
# ----------------------- #
#most of the time title and icon can be the same, but icon for mail was envelope so I divided it
social: 
  - title: Mail
    icon: envelope
    url: "&#109;&#097;&#105;&#108;&#116;&#111;:&#105;&#110;&#102;&#111;&#064;&#098;&#099;&#045;&#119;&#105;&#110;&#101;&#115;&#046;&#099;&#111;&#109;"
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap
#  - title: linkedin
#    url: 


# Build settings
markdown: kramdown
theme: jekyll-paginate #minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - .git
  - .gitignore

